apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-app
  labels:
    app: green-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: green-app
  template:
    metadata:
      labels:
        app: green-app
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo
        args:
          - "-listen=:8081"
          - "-text=I am green"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: green-app-service
  labels:
    app: green-app
spec:
  type: ClusterIP
  selector:
    app: green-app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: green-app-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "30"
spec:
  ingressClassName: nginx
  rules:
  - host: testapp.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: green-app-service
            port:
              number: 8081
